### ISSUE TITLE
best practices for host wordpress app

### ISSUE THREAD

**Issue by dinf-uern** [tsuru/tsuru#1177]
what are the best practices for maintain the content of wordpress (plugins, themes, uploads, images) running in a container with tsuru? is it possible to share a volume from the host or mount a nfs volume into the container?

**Comment by cezarsa** [comment]
Running wordpress applications as tsuru apps needs some consideration since they don't really adhere to twelve-factor practices. There are two options, the first is to never update or install plugins and themes when running on tsuru, they should be installed locally and then pushed to tsuru.
The other option is what you suggested, using sharedfs for plugins and themes. Unfortunately it's not throughly documented yet (see #985). Basically you need to add to your tsuru.conf:
```
docker:
  sharedfs:
    hostdir: /shared
    mountpoint: /shared
    app-isolation: true
```
