### ISSUE TITLE
ssh timeout on experimental installer with digitalocean drive

### ISSUE THREAD

**Issue by avelino** [tsuru/tsuru#1487]
Tsuru client version: 1.1.1
OS: Debian 8 x64

Conf:
```
driver:
    name: digitalocean
    options:
        digitalocean-access-token: -
        digitalocean-ssh-port: 22
        digitalocean-ssh-user: root
        digitalocean-image: debian-8-x64
        digitalocean-size: 512mb
        digitalocean-ipv6: false
        digitalocean-private-networking: false
        digitalocean-region: nyc1
        digitalocean-backups: false
        digitalocean-ssh-key-fingerprint: -
```

Error:
```
root@tsuru-node-01:~# ./tsuru install -c test.conf
Running pre-install checks...
Running pre-create checks...
Creating machine...
(tsuru-1) Creating SSH key...
(tsuru-1) Creating Digital Ocean droplet...
(tsuru-1) Waiting for IP address to be assigned to the Droplet...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Ignoring error on machine creation: Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceededWaiting for SSH to be available...
Error: failed to provision components machines: failed to provision machines: error creating machine Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
root@tsuru-node-01:~#
```

**Note: Running tsuru client in macOS didn't had this problem**
