### ISSUE TITLE
HTTP API based Router

### ISSUE THREAD

**Issue by andrestc** [tsuru/tsuru#1572]
This issue is to track the definition of a base router API contract and the addition of a generic api based router implementation on tsuru api. These will make easier to add new routers (their specific code will live outside tsuru code such as a [TCP router](https://github.com/tsuru/tsuru/issues/983).

The conf for setting up a router would be such as:

``` yml
routers:
  my-generic-router:
    type: generic # (or api?...)
    endpoint: http://my-router-endpoint/v1
```

The generic router type expects the endpoint to implement a certain api contract to be able to provide all the Router interface functionality (we will need to rethink show we check for specific functionality, such [as TLS](https://github.com/tsuru/tsuru/blob/master/app/app.go#L1808))

We have also discussed and agreed on removing our `fusis` implementation and moving it a separated repository that will implement the router http api.
