### ISSUE TITLE
`tsuru install` fails with "This node is already part of a swarm."

### ISSUE THREAD

**Issue by NathanFlurry** [tsuru/tsuru#1606]
Hello,

I'm trying to install Tsuru using the experimental `tsuru install` and it seems to fail when attempting to add the second node to the swarm. Here is the log:

```
$ tsuru install -c tsuru-config.yml
Running pre-install checks...
Running pre-create checks...
Creating machine...
(tsuru-1) No SSH key specified. Assuming an existing key at the default location.
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(upstart)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
Waiting for SSH to be available...
Detecting the provisioner...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Creating registry certificate...
Uploading registry certificate...
Running pre-create checks...
Creating machine...
(tsuru-2) No SSH key specified. Assuming an existing key at the default location.
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(upstart)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
Waiting for SSH to be available...
Detecting the provisioner...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Uploading registry certificate...
Error: failed to setup swarm cluster: machine tsuru-2 failed to join swarm: API error (503): {"message":"This node is already part of a swarm. Use \"docker swarm leave\" to leave this swarm and join another one."}
```

And here is my config:
```
hosts:
    core:
        size: 2
        driver:
            options:
                generic-ip-address: ["<ip for node 1"]
    apps:
        size: 1
        dedicated: true
        driver:
            options:
                generic-ip-address: ["<ip for node 2>"]
driver:
    name: generic
    options:
        generic-ssh-port: 22
        generic-ssh-user: root
```

I am running both servers on Ubuntu 14.04 x64 on Vultr. My Tsuru CLI version is 1.2.0.

Thanks!
