### ISSUE TITLE
support custom http headers on healthchecks

### ISSUE THREAD

**Issue by andrestc** [tsuru/tsuru#1693]
We should support setting custom http headers for healthchecks on tsuru.yml, example: suppose you have the following configuration in an app's tsuru.yaml:

```
healthcheck:
  path: /healthcheck
  method: GET
  status: 200
  request_headers:
    - Host: myapp.globoi.com
    - TSURU_HC: 1
```

Whenever testing the application healthcheck tsuru would send a request to `/healthcheck` adding both the `Host` and the `TSURU_HC` http headers.
