### ISSUE TITLE
tsuru.conf: split gandalf url configurations

### ISSUE THREAD

**Issue by flavianmissi** [tsuru/tsuru#202]
e.g.:

```
git:
    url: gandalf-server.com
    port: 8080
    protocol: http
```

Only the `port` part is optional.
