### ISSUE TITLE
Kubernetes: Processes groups

### ISSUE THREAD

**Issue by andrestc** [tsuru/tsuru#2212]
It is desirable to be able to group different processes (lines on the Procfile) to:
1. Schedule them to the same node
2. Share namespaces 

As discussed previously, we can achieve this by extending the `tsuru.yaml` specification to hold provisioner specific configuration (as this feature would be only available on Kubernetes for now).

For example, the app has the following Procfile entries:

```
web: ...
sidecar: ...
mysql: ...
```

The user can configure how they are going to be scheduled on `tsuru.yaml`:
```
kubernetes:
  groups:
    group1:
      web:
      sidecar:
    group2:
      mysql:
```

A deploy using this yaml file would create two different Kubernetes deployments, one that manages a pod with 2 containers (group1 with web and sidecar containers) and one that manages a pod with a single container (group2 with the mysql container).

There are some challanges and design decisions to make, such as:

- How would a `unit add` work?

We can require that the name of the group is also the name of one of the processes in that group, which is a special process (just like how processes and thread groups work on Linux). So the number of units of that group would actually be the number of units of that process. In the example above, instead of `group1` and `group2`, groups would be called `web` and `mysql`. 

```
kubernetes:
  groups:
    web:
      web:
      sidecar:
    mysql:
      mysql:
```

We could omit the second group, as the default would be to each process to live on its own group. So the yaml above has the same effect as:

```
kubernetes:
  groups:
    web:
      web:
      sidecar:
```

- How to choose the container on which an `app shell` will connect?

Since the processes names are still going to be unique, I think this is not a problem.

There are probably other open questions. I'll update the issue as we discuss it.
