### ISSUE TITLE
Kubernetes: extended ports configuration

### ISSUE THREAD

**Issue by andrestc** [tsuru/tsuru#2213]
It is a common request to be able to define multiple ports per processes. This issue extends the proposed yaml structure on #2212 to be able to specify different ports and also protocols to be used in Kubernetes.

Once again, the app has the following Procfile:

```
web: ...
sidecar: ...
mysql: ...
```

The user is able to configure different and multiple ports per process as:

```yaml
kubernetes:
  groups:
    web:
      web:
        ports:
          - name: apache-http # an optional name for the port 
            protocol: http
            port: 80 # The port that is going to be exposed on the router.
            target_port: 8888 # The port on which the application listens on.
          - name: apache-https
            protocol: https
            port: 443
            target_port: 4444
      sidecar:
        ports:
          - name: metrics-https
            protocol: http # port defaults to the protocol default port (when available)
    mysql:
      mysql:
        ports:
          - protocol: tcp # name defaults to <process>-<protocol>, mysql-tcp in this case
            port: 3306 # target_port defaults to the same value as port
```

This will require some changes on how tsuru interacts with routers. 
1. Each router needs a way to specify what protocols it suports
2. We could create some default domain names for some protocols, such as: <process>.<group>.<domain>. For example: `web.web.myrouter.cloud.com` and `sidecar.web.myrouter.cloud.com`. (Related to https://github.com/tsuru/tsuru/issues/1499)

**Comment by ggarnier** [comment]
We could also support selecting which ports will be added as liveness/readiness probes.

**Comment by ggarnier** [comment]
We could support disabling port expose for a specific process using an empty array:

```
kubernetes:
  groups:
    mypod:
      web:
        ports:
          - target_port: 8000
      worker:
        ports: []
```

Processes declared in `Procfile` and omitted in this config would expose the default port, and processes declared in this config with an empty array wouldn't expose any ports.

What do you think of this approach?

**Comment by andrestc** [comment]
If `tsuru.yaml` has nothing configurated under `kubernetes:` we should keep the current behavior (first process or the process called web exposes the `8888`).
If `tsuru.yaml` has anything under `kubernetes:` I think its better if we require that every open port should be explicitly set (more secure and Its what I would expect). So the following yaml means that no port is being exposed on the worker process.

```
kubernetes:
  groups:
    mypod:
      web:
        ports:
          - target_port: 8000
      worker:
````
