### ISSUE TITLE
Provisioning Stuck at  Waiting for Docker Registry to become responsive

### ISSUE THREAD

**Issue by drpdishant** [tsuru/tsuru#2324]
While provisioning on ubuntu-18.04 machines, it is stuck at 
`Waiting for Docker Registry to become responsive at "https://192.168.1.40:5000"...
`
I checked the events using `docker system events` on the docker host.
check the output here, https://pastebin.com/PKjJRrYi
It implies that it is continously trying to create and recreate, because of that the Regsistry never comes up.
Following is my config.yml file.
```

hosts:
    core:
        size: 1
        driver:
            options:
                generic-ip-address: ["192.168.1.40"]
                generic-ssh-key: ["/home/addweb/.vagrant.d/insecure_private_key"]
    apps:
        size: 1
        driver:
            options:
                generic-ip-address: ["192.168.1.41"]
                generic-ssh-key: ["/home/addweb/.vagrant.d/insecure_private_key"]
driver:
    name: generic
    options:
        generic-ssh-port: 22
        generic-ssh-user: vagrant
```

I am using vagrant machines. as tsuru-core and tsuru-apps server.

It is due because, the container isn't able to get the certificate files from the defined path.

**Comment by tancou** [comment]
I managed to install tsuru with this bug.

My previous configuration :

- 1 debian client on `10.10.1.127/24`, with tsuru client installed on it, config + ssh private key
- 6 debian VM for the tsuru cluster on `10.10.1.[10-15]/24`

With that configuration, the bug `Waiting for Docker Registry to become responsive` occurred every time and stuck all the deployment .

The docker registry failed to start on the first core node because of the `certs` folder missing.

When the tsuru client deploys the certs folder, it copies it to the `/home/{generic-ssh-user}/certs/{IP_of_the_tsuru_CLIENT}:5000/` instead of `/home/{generic-ssh-user}/certs/{CLUSTER_PRIVATE_ADDR}:5000/` specified on the `install-compose.yml`.

In my case, this results of a folder `/home/myuser/certs/10.10.1.127:5000/` instead of `/home/myuser/certs/10.10.1.10:5000/`

I succeeded to deploy the tsuru cluster running all the commands from the first node (`10.10.1.10`), where the docker registry is initially deployed (as so `IP_of_the_tsuru_CLIENT` matches `CLUSTER_PRIVATE_ADDR`).

I am a new-user of tsuru but I think there are two big issues with that :
- I have to install first a tsuru client on one core node before deploy, which means that first I have to deploy a ssh key over all other VM from a VM that is on the cluster. If i forget to remove the key, it should result on security issue. If I don't backup the key before that, I could probably not be able to ssh anymore on all other nodes?
- What if I want to duplicate my docker registry over other nodes, do I have to copy `{CLUSTER_PRIVATE_ADDR}:5000` on all nodes with the IP of those other instances?

**Comment by tancou** [comment]
Well, I found a way to bypass the wrong IP used when certs are deployed.

I added `private-ip-interface: eth0` option with the name of my primary network interface.

Try to change your `config.yml` file :
```
hosts:
    core:
        size: 1
        driver:
            options:
                generic-ip-address: ["192.168.1.40"]
                generic-ssh-key: ["/home/addweb/.vagrant.d/insecure_private_key"]
    apps:
        size: 1
        driver:
            options:
                generic-ip-address: ["192.168.1.41"]
                generic-ssh-key: ["/home/addweb/.vagrant.d/insecure_private_key"]
driver:
    name: generic
    private-ip-interface: eth0
    options:
        generic-ssh-port: 22
        generic-ssh-user: vagrant
```
