### ISSUE TITLE
Rebalance / node-autoscale move units to the same node it is running

### ISSUE THREAD

**Issue by rodolfo3** [tsuru/tsuru#2329]
**Description**

Run a `node-rebalance` or `node-autoscale-run` move units to the same node it is already running.
It should only move units to remove from a node to add to another.

**Steps to reproduce**
> 1. Configure autoscale with rebalance:
```
$ tsuru node-autoscale-info
Rules:
+------+---------------------+------------------+------------------+--------------------+---------+
| Pool | Max container count | Max memory ratio | Scale down ratio | Rebalance on scale | Enabled |
+------+---------------------+------------------+------------------+--------------------+---------+
| corp | 0                   | 1.0000           | 1.3300           | true               | true    |
+------+---------------------+------------------+------------------+--------------------+---------+
```

> 2. Run autoscale
```
$ tsuru node-autoscale-run
```

> 3. It moves units to the same node it is running
```
Moved unit 4ec806bc2746f959857478ffc2682d7522a53e67b2c3b9db420ff22276028897 -> c6f7d78c08bf64ce3900aa9039ec3c0f8d6332033f75f739416fb1e0f242d9e6 for "sentry9-prd" from ip-10-0-3-70.ec2.internal -> ip-10-0-3-70.ec2.internal
Moved unit 11c1b3a1125110165be5ef8d3451e0026403425e349646b76d679fbc3a9d502e -> c18d07ee27990a840fde15c2895046dd4cd4fab0c1da04954f0fc237e736438d for "metabase-prd" from ip-10-0-3-70.ec2.internal -> ip-10-0-3-70.ec2.internal
```

**Expected result**
Only move units to new nodes, not move units to the same node.
Sometimes it do both (move some to the same node, others to new nodes)

The same happen when running `tsuru node-rebalance`.

**Environment information**

* Tsuru installation method:
 - Docker Compose

* Tsuru API version
- docker image: `tsuru/api:release-1.7.0`
- tsurud version: `tsurud version 1.7.0.`

* Tsuru client version
```
$ tsuru --version
tsuru version 1.6.0.
```

**Cluster information**

* Node provider
`EC2`

* Machine type
`VM (Ubuntu 18.04)`

* Machine specs
`m5.xlarge`

* Provisioner
`default`

* Docker version
> On server
```
$ docker --version
Docker version 18.09.7, build 2d0083d
```
> On nodes
```
$ docker --version
Docker version 19.03.1, build 74b1e89
```

* tsuru.conf docker configuration
```
docker:
    collection: docker_containers
    port-allocator: tsuru
    registry: $REGISTRY_ADDR:$REGISTRY_PORT
    repository-namespace: tsuru
    image-history-size: 5
    max-layers: 10 #The maximum number of layers in Docker images. This number represents the number of times that Tsuru will reuse the previous image on application deployment. The default value is 10.
    router: hipache
    max-time: 240
    cluster:
        mongo-url: $MONGODB_ADDR:$MONGODB_PORT
        mongo-database: cluster
    healing:
        heal-nodes: true
        wait-new-time: 300
        active-monitoring-interval: 20
        max-failures: 15
        heal-containers-timeout: 30
        disabled-time: 300
    limit:
        actions-per-host: 1
    auto-scale:
        enabled: true
        prevent-rebalance: true
        scale-down-ratio: 1.33
        wait-new-time: 360
        run-interval: 300
    scheduler:
        total-memory-metadata: totalMemory
        max-used-memory: 1
```
