### ISSUE TITLE
Platform-Info should give more information

### ISSUE THREAD

**Issue by guilhermebr** [tsuru/tsuru#2375]
The `platform-info` command only shows the list of build versions of each platform.

It was be great if the command also show information about the platform content, like supported versions, configuration files supported, etc..

One way to do this is creating a yaml file `.spec` inside each platform, with these informations.
ex:

```yaml
name: python
default_version: "2.7.14"
supported_versions: 
    - 2.7.14
    - 3.5.5
    - pypy2.7-5.10.0
requirement_files:
    - requirements.txt
    - requirements.apt
version_file: .python_version
envs: 
    - PYTHON_VERSION
    - PYTHON_PIP_VERSION
```

and in tsuru at platform-build stage, parse this file and save the information to show on `tsuru platform-info python`
