### ISSUE TITLE
imagePullSecrets not filled with private registry

### ISSUE THREAD

**Issue by eliottness** [tsuru/tsuru#2705]
**Description**

👋 I can't seem to make the private registry image pull to work when deploying a helloworld app. The push via the deploy-agent is working but after running `tsuru app deploy -i registry.myserver.com/image-name -a helloworld`, the pod is in ImagePullBackOff because it can't authenticate on the registry.

**Steps to reproduce**

I simply followed this guide: https://docs.tsuru.io/latest/using/docker-image.html

**Actual result**

After `tsuru app deploy -i registry.myserver.com/image-name -a helloworld`:
Pod is in ImagePullBackOff with image pull error with status code 401.

**Expected result**

I would expect tsuru to have created the secret in the right namespace and filled the `imagePullSecrets` field in the deployment. Just like I saw it in [`deploy.go`](https://github.com/tsuru/tsuru/blob/main/provision/kubernetes/deploy.go)

**Environment information**

* Nodes OS: all on Debian 12: `Linux XXXXXX 6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.37-1 (2023-07-03) x86_64 GNU/Linux`
* Installation method: I pieced the parts of the helm-charts I needed. I will detail below
* Tsuru API version: 1.20.8
* Tsuru client version: 1.20.8

**Cluster information**

* Node provider: unmanaged
* Machine type: VM
* Machine specs: 4CPU & 16Go RAM
* Provisioner: `kubernetes`
* Kubernetes version: `v1.27.10+rke2r1`

**Helm Chart Install**

I already had a mongodb and a [harbor](https://goharbor.io/) registry deployed. And I saw lot of secrets in plain text in the helm values so I decided to deploy the `kubernetes-router` & `deploy-agent` charts manually and fully copy the `tsuru-api` chart to be able to mount the `tsuru.conf` file from a secret instead of from a config map.

<details>
  <summary>tsuru.conf</summary>

  ```yml
    listen: "0.0.0.0:8080"
    host: https://tsuru.k8s.XXX.com
    useTLS: false
    auth:
      user-registration: true
      scheme: oidc
      oidc:
        client-id: "{{ .client_id }}"
        client-secret: "{{ .client_secret }}"
        scopes: 
          - email
          - profile
          - openid
          - offline_access
        auth-url: "https://authentik.k8s.XXX.com/application/o/authorize/"
        token-url: "https://authentik.k8s.XXX.com/application/o/token/"
        info-url: "https://authentik.k8s.XXX.com/application/o/userinfo/"
        jwks-url: https://authentik.k8s.XXX.com/application/o/tsuru/jwks/
        callback-port: 13426
        groups-in-claims: true
    
    admin-team: "authentik Admins"
    
    quota:
      apps-per-user: 0
      apps-per-team: 0
      units-per-app: 0
    
    database:
      url: mongodb://{{ .tsurudb_username }}:{{ .tsurudb_password }}@mongodb.ci-cd.svc.cluster.local:27017/tsurudb
      driver: mongodb
      name: tsurudb
    
    queue:
      mongo-url: mongodb://{{ .tsuruqueuedb_username }}:{{ .tsuruqueuedb_password }}@mongodb.ci-cd.svc.cluster.local:27017/tsuruqueuedb
      mongo-database: tsuruqueuedb
    
    smtp:
      server: mail-svc.default.svc.cluster.local
      user: noreply@XXX.com
    
    routers:
      ingress:
        type: api
        default: true
        api-url: http://kubernetes-router.ci-cd.svc.cluster.local/api/ingress
        headers:
          Authorization: "Basic {{ printf "%s:%s" .router_username .router_password | b64enc }}"
    
    provisioner: kubernetes
    debug: true
    log:
      disable-syslog: true
    
    clusters:
      defaults:
        build-service-address: "dns:///tsuru-deploy-agent.ci-cd.svc.cluster.local:80"
        registry: harbor.k8s.XXX.com/tsuru
        build-service-tls: "false"
        disable-default-node-selector: "true"
        job-event-creation: "false"
        namespace: default
        docker-config-json: >-
          {
            "auths":{
              "harbor.k8s.XXX.com":{
                "username":"{{ .registry_username }}",
                "password":"{{ .registry_password }}",
                "auth":"{{ printf "%s:%s" .registry_username .registry_password | b64enc }}"
              }
            }
          }
    
    docker:
      registry: harbor.k8s.XXX.com
      registry-auth:
        username: {{ .registry_username }}
        password: {{ .registry_password }}
      resolve-registry-name: true
      gc:
        dry-run: false
      router: ingress
      cluster:
        storage: mongodb
        mongo-url: mongodb://{{ .tsurudb_username }}:{{ .tsurudb_password }}@mongodb.ci-cd.svc.cluster.local:27017/tsurudb
        mongo-database: tsurudb
  ```
</details>

<details>
  <summary>kubernetes-router-helm-values.yml</summary>

  ```yml
    controllerModes:
      - ingress

    ingressExpose:
      domain: api.XXX.com

    arguments:
      - -k8s-namespace
      - default
      - -k8s-annotations
      - cert-manager.io/cluster-issuer=letsencrypt

    service:
      type: ClusterIP
  ```
</details>

<details>
  <summary>deploy-agent-helm-values.yml</summary>

  ```yml
    deployAgent:
      volumeMounts:
        - name: docker-config
          mountPath: /root/.docker/config.json
          subPath: .dockerconfigjson
      env:
        - name: DOCKER_CONFIG
          value: /root/.docker

    volumes:
      - name: docker-config
        secret:
          secretName: harbor-registry-auth

    buildkit:
      image:
        tag: v0.13.2
      env:
        - name: DOCKER_CONFIG
          value: /root/.docker
      volumeMounts:
        - name: docker-config
          mountPath: /root/.docker/config.json
          subPath: .dockerconfigjson
      config: |
        # Buildkitd config file
        # https://github.com/moby/buildkit/blob/master/docs/buildkitd.toml.md

        debug = true
        trace = true

        [dns]
          nameservers=[]

        [grpc]
          address = [
            "tcp://0.0.0.0:8081",
            "unix:///run/buildkit/buildkitd.sock",
          ]

        [worker.containerd]
          enabled = false

        [worker.oci]
          enabled = true
          gc = false

          # NOTE: Force x86_64 arch as Tsuru doesn't support different ones yet.
          platforms = [
            "linux/amd64"
          ]
  ```

</details>

I believe the only wierd thing I did here is in the `tsuru.conf` file where I did `clusters:defaults:registry = harbor.k8s.XXX.com/tsuru` because Harbor does not support to push top level images so I had to create what they call a "library" named tsuru to store images.
