### ISSUE TITLE
provision/juju: unit state goes "pending" when agent state is "charm-upgrade-error"

### ISSUE THREAD

**Issue by fsouza** [tsuru/tsuru#357]
Example of Juju output:

```
my-service:
    charm: local:precise/python-0
    relations: {}
    units:
      my-service/2:
        agent-state: charm-upgrade-error
        machine: 4833
        public-address: 10.10.10.10
```
