### ISSUE TITLE
App not detected by tsuru

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#636]
```
Dec  5 14:41:55 api 2013-12-05T14:41:55+01:00 api tsr[11935]: error on start the app test - Container port 8888 is not mapped to any host port
Dec  5 14:41:56 api 2013-12-05T14:41:56+01:00 api tsr[11935]: Error handling "regenerate-apprc" for the app "test": all units must be started.
```

I'm using a remote docker node not hosted on the same machine that hosts tsuru api:

```
docker:
  servers:
    - http://docker-registry.mynet.lan:4243
  collection: docker
  repository-namespace: mycloud
  router: hipache
  deploy-cmd: /var/lib/tsuru/deploy
  ssh-agent-port: 4545
  run-cmd:
    bin: /var/lib/tsuru/start
    port: "8888"
  ssh:
    add-key-cmd: /var/lib/tsuru/add-key
    public-key: /home/ubuntu/.ssh/id_rsa.pub
    user: ubuntu
```

on docker's node, the container is running properly:
    $ docker ps
    CONTAINER ID        IMAGE                 COMMAND                CREATED             STATUS              PORTS               NAMES
    26127ecd1c15        mycloud/test:latest   /bin/bash -c /var/li   10 minutes ago      Up 10 minutes       8888/tcp            mad_poincare        

and i'm able to see the application output (a simple phpinfo()):

```
$ curl http://172.17.0.44:8888 -s | grep 'PHP Version'
<a href="http://www.php.net/"><img border="0" src="/index.php?=PHPE9568F34-D428-11d2-A769-00AA001ACF42" alt="PHP Logo" /></a><h1 class="p">PHP Version 5.4.6-1ubuntu1</h1>
<tr><td class="e">PHP Version </td><td class="v">5.4.6-1ubuntu1 </td></tr>
```

does hipache need to be executed on the same docker host? Actually i have hipache placed on the tsuru api server
