### ISSUE TITLE
App configuration through tsuru.yaml

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#686]
Apps should be configurabile (as much as possible) through the use of app.yaml.

For example, something like this:

```
app:
   units: 3
   cnames:
      - www.mydomain.com
      - other.domain.org

services:
   - mydatabase

hooks:
   restart:
      after-each:
         - ls > /tmp/test.tmp
   build:
      - ls > /tmp/test.tmp
```

this is really usefull for scripted push or to revert to a previous state via git.
A developer for an online toy store would like to create a git branch for Christmas with app.yaml configured to use 10 units, then in February will switch back to the main branch with just 2 units without using tsuru client.

Another example would be a git branch/commit with some services bound to the app and some cnames used for development. When development is done, switch back to the master branch with main database and production domain as cname
