### ISSUE TITLE
`ro-host` not used

### ISSUE THREAD

**Issue by bobobo1618** [tsuru/tsuru#807]
Inside the Tsuru configuration file, I'm essentially using this:

```
git:
  unit-repo: /home/application/current
  api-server: http://{{ec2_private_ip_address}}:8000
  rw-host: git.{{controller_zone}}
  ro-host: {{ec2_private_ip_address}}
```

However when attempting to push an application, I get errors that look like this:

```
Counting objects: 72, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (61/61), done.
Writing objects: 100% (72/72), 16.80 KiB | 0 bytes/s, done.
Total 72 (delta 30), reused 0 (delta 0)
remote: Cloning into '/home/application/current'...
remote: fatal: unable to connect to {{controller_zone}}:
remote: git.{{controller_zone}}[0: {{public_ip_address}}]: errno=Connection timed out
remote: 
remote: 
remote:  ---> App will be restarted, please check its logs for more details...
remote: 
```

which show that Tsuru is attempting to build a unit using the `rw` Git host instead of the `ro` Git host that it had been given.
