### ISSUE TITLE
Environment vars on tsuru.yml

### ISSUE THREAD

**Issue by morpheu** [tsuru/tsuru#912]
tsuru.yml should support some kind of pre-defined vars per environment. Eg:

```
env:
  prod:
    - MAX_PROCS: 5
    - WHATEVER_VAR: 2
  dev:
    - MAX_PROCS: 1
    - WHATEVER_VAR: 1
  default:
     - MY_VAR_ON_ALL_ENVS: 3
```

Some premisses to this functionality:
- User just have to set some var, like TSURU_ENV, via tsuru env-set to corresponding environment on app.yml.  
- Default variables on app.yml always gonna be loaded.
- Env defined vars on app.yml will merge with default vars task.
- Any variable set via tsuru env-set and service defined variables will merge with variables defined on app.yml file.
